force-app/main/default/objects/Guild__c/Guild__c.object-meta.xml
<CustomObject>
    <label>Guild</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guilds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/Superhero_Mission__c.object-meta.xml
<CustomObject>
    <label>Superhero Mission</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Superhero Missions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Superhero_Mission__c/fields/Complexity_Rank__c.field-meta.xml
<CustomField>
    <fullName>Complexity_Rank__c</fullName>
    <defaultValue>&quot;D&quot;</defaultValue>
    <label>Complexity Rank</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rank</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Guild__c.field-meta.xml
<CustomField>
    <fullName>Guild__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Guild</label>
    <referenceTo>Guild__c</referenceTo>
    <relationshipLabel>Superhero Missions</relationshipLabel>
    <relationshipName>Superhero_Missions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Superhero_Mission__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
                <default>true</default>
                <label>Available</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Rank.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>S</fullName>
    </customValue>
    <customValue>
        <fullName>A</fullName>
    </customValue>
    <customValue>
        <fullName>B</fullName>
    </customValue>
    <customValue>
        <fullName>C</fullName>
    </customValue>
    <customValue>
        <fullName>D</fullName>
    </customValue>
    <masterLabel>Rank</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SuperheroMissionController.cls
public with sharing class SuperheroMissionController {

    @AuraEnabled(cacheable=true)
    public static List <Superhero_Mission__c> getMissions(Integer offset, Integer numberOfRecords) {

        System.debug(offset);

        List<Superhero_Mission__c> result = [SELECT Complexity_Rank__c, Subject__c, Guild__r.Name, Status__c
            FROM Superhero_Mission__c
            ORDER BY CreatedDate ASC
            LIMIT :numberOfRecords
            OFFSET :offset];

        System.debug(result);
        return result;
    }

}